# Generated by Django 4.0.1 on 2022-02-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_bio_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='github',
            field=models.URLField(blank=True, null=True, verbose_name='github'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='linkedin'),
        ),
    ]
