# Generated by Django 4.0.1 on 2022-02-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsstory_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='category',
            field=models.CharField(default='coding', max_length=200),
        ),
    ]
