# Generated by Django 4.0.1 on 2022-02-18 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_snippet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
